// <auto-generated />
using System;
using Buoi1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buoi1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316043314_UpdateHinhAnh")]
    partial class UpdateHinhAnh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buoi1.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTaiThoiDiemDat")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonHangId = 1,
                            GiaTaiThoiDiemDat = 38900000m,
                            SanPhamId = 2,
                            SoLuong = 1
                        },
                        new
                        {
                            Id = 2,
                            DonHangId = 2,
                            GiaTaiThoiDiemDat = 52990000m,
                            SanPhamId = 8,
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("Buoi1.Models.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DonHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NgayDat = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 38900000m,
                            TrangThai = "HoanThanh",
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            NgayDat = new DateTime(2024, 1, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 52990000m,
                            TrangThai = "DangGiao",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Buoi1.Models.HangXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HangXes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenHang = "Honda"
                        },
                        new
                        {
                            Id = 2,
                            TenHang = "Yamaha"
                        },
                        new
                        {
                            Id = 3,
                            TenHang = "Suzuki"
                        });
                });

            modelBuilder.Entity("Buoi1.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaKichHoat")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaKichHoat = true,
                            Email = "admin@xemaystore.com",
                            MatKhau = "admin123",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DaKichHoat = true,
                            Email = "user1@gmail.com",
                            MatKhau = "user123",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "user1",
                            VaiTro = "User"
                        });
                });

            modelBuilder.Entity("Buoi1.Models.XeMay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,0)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHangXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("MauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("N/A");

                    b.Property<int>("NamSanXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2023);

                    b.Property<int>("PhanKhoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaHangXe");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 18900000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+Wave+Alpha",
                            MaHangXe = 1,
                            MauSac = "Do",
                            NamSanXuat = 2024,
                            PhanKhoi = 110,
                            SoLuongTon = 10,
                            TenSanPham = "Honda Wave Alpha 110"
                        },
                        new
                        {
                            Id = 2,
                            Gia = 38900000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+Air+Blade",
                            MaHangXe = 1,
                            MauSac = "Den",
                            NamSanXuat = 2024,
                            PhanKhoi = 125,
                            SoLuongTon = 8,
                            TenSanPham = "Honda Air Blade 125"
                        },
                        new
                        {
                            Id = 3,
                            Gia = 30900000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+Vision",
                            MaHangXe = 1,
                            MauSac = "Do",
                            NamSanXuat = 2024,
                            PhanKhoi = 110,
                            SoLuongTon = 15,
                            TenSanPham = "Honda Vision 110"
                        },
                        new
                        {
                            Id = 4,
                            Gia = 70900000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+SH+150i",
                            MaHangXe = 1,
                            MauSac = "Trang",
                            NamSanXuat = 2024,
                            PhanKhoi = 150,
                            SoLuongTon = 5,
                            TenSanPham = "Honda SH 150i"
                        },
                        new
                        {
                            Id = 5,
                            Gia = 52900000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+PCX+125",
                            MaHangXe = 1,
                            MauSac = "Den",
                            NamSanXuat = 2024,
                            PhanKhoi = 125,
                            SoLuongTon = 7,
                            TenSanPham = "Honda PCX 125"
                        },
                        new
                        {
                            Id = 6,
                            Gia = 68000000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+CB150R",
                            MaHangXe = 1,
                            MauSac = "Den",
                            NamSanXuat = 2023,
                            PhanKhoi = 150,
                            SoLuongTon = 4,
                            TenSanPham = "Honda CB150R"
                        },
                        new
                        {
                            Id = 7,
                            Gia = 46900000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+Winner+X",
                            MaHangXe = 1,
                            MauSac = "Trang",
                            NamSanXuat = 2024,
                            PhanKhoi = 150,
                            SoLuongTon = 6,
                            TenSanPham = "Honda Winner X 150"
                        },
                        new
                        {
                            Id = 8,
                            Gia = 52990000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+Exciter+155",
                            MaHangXe = 2,
                            MauSac = "Xanh",
                            NamSanXuat = 2024,
                            PhanKhoi = 155,
                            SoLuongTon = 9,
                            TenSanPham = "Yamaha Exciter 155 VVA"
                        },
                        new
                        {
                            Id = 9,
                            Gia = 53990000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+NVX+155",
                            MaHangXe = 2,
                            MauSac = "Den",
                            NamSanXuat = 2024,
                            PhanKhoi = 155,
                            SoLuongTon = 7,
                            TenSanPham = "Yamaha NVX 155 VVA"
                        },
                        new
                        {
                            Id = 10,
                            Gia = 48990000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+Grande+125",
                            MaHangXe = 2,
                            MauSac = "Trang",
                            NamSanXuat = 2024,
                            PhanKhoi = 125,
                            SoLuongTon = 8,
                            TenSanPham = "Yamaha Grande 125 Hybrid"
                        },
                        new
                        {
                            Id = 11,
                            Gia = 31490000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+Janus+125",
                            MaHangXe = 2,
                            MauSac = "Hong",
                            NamSanXuat = 2023,
                            PhanKhoi = 125,
                            SoLuongTon = 12,
                            TenSanPham = "Yamaha Janus 125"
                        },
                        new
                        {
                            Id = 12,
                            Gia = 38990000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+Freego+125",
                            MaHangXe = 2,
                            MauSac = "Xanh",
                            NamSanXuat = 2023,
                            PhanKhoi = 125,
                            SoLuongTon = 6,
                            TenSanPham = "Yamaha Freego 125"
                        },
                        new
                        {
                            Id = 13,
                            Gia = 98000000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+R15+V4",
                            MaHangXe = 2,
                            MauSac = "Xanh",
                            NamSanXuat = 2024,
                            PhanKhoi = 155,
                            SoLuongTon = 3,
                            TenSanPham = "Yamaha R15 V4"
                        },
                        new
                        {
                            Id = 14,
                            Gia = 94000000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+MT-15+V2",
                            MaHangXe = 2,
                            MauSac = "Den",
                            NamSanXuat = 2024,
                            PhanKhoi = 155,
                            SoLuongTon = 4,
                            TenSanPham = "Yamaha MT-15 V2"
                        },
                        new
                        {
                            Id = 15,
                            Gia = 52990000m,
                            HinhAnh = "https://placehold.co/400x300?text=Suzuki+Raider+R150",
                            MaHangXe = 3,
                            MauSac = "Trang",
                            NamSanXuat = 2023,
                            PhanKhoi = 150,
                            SoLuongTon = 5,
                            TenSanPham = "Suzuki Raider R150 Fi"
                        },
                        new
                        {
                            Id = 16,
                            Gia = 28500000m,
                            HinhAnh = "https://placehold.co/400x300?text=Suzuki+Hayate+125",
                            MaHangXe = 3,
                            MauSac = "Xam",
                            NamSanXuat = 2023,
                            PhanKhoi = 125,
                            SoLuongTon = 8,
                            TenSanPham = "Suzuki Hayate 125"
                        },
                        new
                        {
                            Id = 17,
                            Gia = 21990000m,
                            HinhAnh = "https://placehold.co/400x300?text=Suzuki+Address+110",
                            MaHangXe = 3,
                            MauSac = "Trang",
                            NamSanXuat = 2023,
                            PhanKhoi = 110,
                            SoLuongTon = 10,
                            TenSanPham = "Suzuki Address 110"
                        },
                        new
                        {
                            Id = 18,
                            Gia = 79000000m,
                            HinhAnh = "https://placehold.co/400x300?text=Suzuki+GSX-R150",
                            MaHangXe = 3,
                            MauSac = "Xanh",
                            NamSanXuat = 2023,
                            PhanKhoi = 150,
                            SoLuongTon = 3,
                            TenSanPham = "Suzuki GSX-R150"
                        },
                        new
                        {
                            Id = 19,
                            Gia = 37900000m,
                            HinhAnh = "https://placehold.co/400x300?text=Honda+Lead+125",
                            MaHangXe = 1,
                            MauSac = "Do",
                            NamSanXuat = 2024,
                            PhanKhoi = 125,
                            SoLuongTon = 9,
                            TenSanPham = "Honda Lead 125"
                        },
                        new
                        {
                            Id = 20,
                            Gia = 21490000m,
                            HinhAnh = "https://placehold.co/400x300?text=Yamaha+Sirius+115",
                            MaHangXe = 2,
                            MauSac = "Den",
                            NamSanXuat = 2023,
                            PhanKhoi = 115,
                            SoLuongTon = 14,
                            TenSanPham = "Yamaha Sirius 115 Fi"
                        });
                });

            modelBuilder.Entity("Buoi1.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("Buoi1.Models.DonHang", "DonHang")
                        .WithMany("ChiTiets")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buoi1.Models.XeMay", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Buoi1.Models.XeMay", b =>
                {
                    b.HasOne("Buoi1.Models.HangXe", "HangXe")
                        .WithMany("XeMays")
                        .HasForeignKey("MaHangXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangXe");
                });

            modelBuilder.Entity("Buoi1.Models.DonHang", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("Buoi1.Models.HangXe", b =>
                {
                    b.Navigation("XeMays");
                });
#pragma warning restore 612, 618
        }
    }
}
