// <auto-generated />
using System;
using Buoi1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buoi1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260316030808_UpdateTableXeMay")]
    partial class UpdateTableXeMay
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buoi1.Models.ChiTietDonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DonHangId")
                        .HasColumnType("int");

                    b.Property<decimal>("GiaTaiThoiDiemDat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SanPhamId")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DonHangId");

                    b.HasIndex("SanPhamId");

                    b.ToTable("ChiTietDonHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DonHangId = 1,
                            GiaTaiThoiDiemDat = 115000000m,
                            SanPhamId = 1,
                            SoLuong = 1
                        });
                });

            modelBuilder.Entity("Buoi1.Models.DonHang", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DonHangs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NgayDat = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TongTien = 115000000m,
                            TrangThai = "HoanThanh",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("Buoi1.Models.HangXe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenHang")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HangXes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenHang = "Honda"
                        },
                        new
                        {
                            Id = 2,
                            TenHang = "Yamaha"
                        },
                        new
                        {
                            Id = 3,
                            TenHang = "Suzuki"
                        });
                });

            modelBuilder.Entity("Buoi1.Models.NguoiDung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("DaKichHoat")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayTao")
                        .HasColumnType("datetime2");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NguoiDungs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DaKichHoat = true,
                            Email = "admin@thinhpc.com",
                            MatKhau = "admin123",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "admin",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            DaKichHoat = true,
                            Email = "user1@gmail.com",
                            MatKhau = "user123",
                            NgayTao = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenDangNhap = "user1",
                            VaiTro = "User"
                        });
                });

            modelBuilder.Entity("Buoi1.Models.XeMay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaBan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaHangXe")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("MauSac")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("N/A");

                    b.Property<int>("NamSanXuat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2024);

                    b.Property<int>("PhanKhoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SoLuongTon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenXe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MaHangXe");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 0m,
                            GiaBan = 115000000m,
                            HinhAnh = "https://cdn.honda.com.vn/motorbikes/october2023/X9A5O5O5O5O5.png",
                            MaHangXe = 1,
                            MauSac = "Đen",
                            NamSanXuat = 2024,
                            PhanKhoi = 150,
                            SoLuongTon = 5,
                            TenSanPham = "",
                            TenXe = "Honda SH 150i"
                        },
                        new
                        {
                            Id = 2,
                            Gia = 0m,
                            GiaBan = 52000000m,
                            HinhAnh = "https://yamaha-motor.com.vn/wp-content/uploads/2023/09/Exciter-155-VVA-moi-Xanh-GP.png",
                            MaHangXe = 2,
                            MauSac = "Xanh GP",
                            NamSanXuat = 2024,
                            PhanKhoi = 155,
                            SoLuongTon = 10,
                            TenSanPham = "",
                            TenXe = "Yamaha Exciter 155 VVA"
                        },
                        new
                        {
                            Id = 3,
                            Gia = 0m,
                            GiaBan = 50000000m,
                            HinhAnh = "https://suzuki.com.vn/images/raider/hinh-anh-xe/xanh-den.png",
                            MaHangXe = 3,
                            MauSac = "Xanh",
                            NamSanXuat = 2023,
                            PhanKhoi = 150,
                            SoLuongTon = 3,
                            TenSanPham = "",
                            TenXe = "Suzuki Raider R150"
                        },
                        new
                        {
                            Id = 4,
                            Gia = 0m,
                            GiaBan = 35000000m,
                            HinhAnh = "https://cdn.honda.com.vn/motorbikes/december2022/Vision_Standard.png",
                            MaHangXe = 1,
                            MauSac = "Trắng",
                            NamSanXuat = 2024,
                            PhanKhoi = 110,
                            SoLuongTon = 15,
                            TenSanPham = "",
                            TenXe = "Honda Vision 2024"
                        },
                        new
                        {
                            Id = 5,
                            Gia = 0m,
                            GiaBan = 29000000m,
                            HinhAnh = "https://yamaha-motor.com.vn/wp-content/uploads/2022/04/Janus-Standard-Trang.png",
                            MaHangXe = 2,
                            MauSac = "Trắng",
                            NamSanXuat = 2024,
                            PhanKhoi = 125,
                            SoLuongTon = 8,
                            TenSanPham = "",
                            TenXe = "Yamaha Janus"
                        });
                });

            modelBuilder.Entity("Buoi1.Models.ChiTietDonHang", b =>
                {
                    b.HasOne("Buoi1.Models.DonHang", "DonHang")
                        .WithMany("ChiTiets")
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Buoi1.Models.XeMay", "SanPham")
                        .WithMany()
                        .HasForeignKey("SanPhamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("SanPham");
                });

            modelBuilder.Entity("Buoi1.Models.XeMay", b =>
                {
                    b.HasOne("Buoi1.Models.HangXe", "HangXe")
                        .WithMany("XeMays")
                        .HasForeignKey("MaHangXe")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HangXe");
                });

            modelBuilder.Entity("Buoi1.Models.DonHang", b =>
                {
                    b.Navigation("ChiTiets");
                });

            modelBuilder.Entity("Buoi1.Models.HangXe", b =>
                {
                    b.Navigation("XeMays");
                });
#pragma warning restore 612, 618
        }
    }
}
