// <auto-generated />
using Buoi1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buoi1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305081826_KhoMoiKeng")]
    partial class KhoMoiKeng
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buoi1.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 55000000,
                            TenSanPham = "VGA ASUS ROG Strix 4090"
                        },
                        new
                        {
                            Id = 2,
                            Gia = 15000000,
                            TenSanPham = "CPU Intel Core i9-14900K"
                        },
                        new
                        {
                            Id = 3,
                            Gia = 6500000,
                            TenSanPham = "RAM G.Skill Trident Z5 RGB 64GB"
                        },
                        new
                        {
                            Id = 4,
                            Gia = 25000000,
                            TenSanPham = "Mainboard MSI Z790 Godlike"
                        },
                        new
                        {
                            Id = 5,
                            Gia = 4500000,
                            TenSanPham = "SSD Samsung 990 Pro 2TB"
                        },
                        new
                        {
                            Id = 6,
                            Gia = 4200000,
                            TenSanPham = "Nguồn Corsair RM1000x"
                        },
                        new
                        {
                            Id = 7,
                            Gia = 4000000,
                            TenSanPham = "Case NZXT H9 Flow"
                        },
                        new
                        {
                            Id = 8,
                            Gia = 32000000,
                            TenSanPham = "Màn hình Samsung Odyssey G9"
                        },
                        new
                        {
                            Id = 9,
                            Gia = 3990000,
                            TenSanPham = "Chuột Razer Viper V3 Pro"
                        },
                        new
                        {
                            Id = 10,
                            Gia = 2990000,
                            TenSanPham = "Phím cơ Akko MOD007"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
