// <auto-generated />
using Buoi1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buoi1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305083249_ThemCotHinhAnh")]
    partial class ThemCotHinhAnh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buoi1.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 55000000,
                            TenSanPham = "VGA ASUS ROG Strix 4090"
                        },
                        new
                        {
                            Id = 2,
                            Gia = 15000000,
                            TenSanPham = "CPU Intel Core i9-14900K"
                        },
                        new
                        {
                            Id = 3,
                            Gia = 6500000,
                            TenSanPham = "RAM G.Skill Trident Z5 RGB 64GB"
                        },
                        new
                        {
                            Id = 4,
                            Gia = 25000000,
                            TenSanPham = "Mainboard MSI Z790 Godlike"
                        },
                        new
                        {
                            Id = 5,
                            Gia = 4500000,
                            TenSanPham = "SSD Samsung 990 Pro 2TB"
                        },
                        new
                        {
                            Id = 6,
                            Gia = 4200000,
                            TenSanPham = "Nguồn Corsair RM1000x"
                        },
                        new
                        {
                            Id = 7,
                            Gia = 4000000,
                            TenSanPham = "Case NZXT H9 Flow"
                        },
                        new
                        {
                            Id = 8,
                            Gia = 32000000,
                            TenSanPham = "Màn hình Samsung Odyssey G9"
                        },
                        new
                        {
                            Id = 9,
                            Gia = 3990000,
                            TenSanPham = "Chuột Razer Viper V3 Pro"
                        },
                        new
                        {
                            Id = 10,
                            Gia = 2990000,
                            TenSanPham = "Phím cơ Akko MOD007"
                        },
                        new
                        {
                            Id = 11,
                            Gia = 32000000,
                            TenSanPham = "VGA Gigabyte AORUS RTX 4080 Super Master"
                        },
                        new
                        {
                            Id = 12,
                            Gia = 24500000,
                            TenSanPham = "VGA MSI RTX 4070 Ti Super Gaming X Trio"
                        },
                        new
                        {
                            Id = 13,
                            Gia = 29000000,
                            TenSanPham = "VGA Sapphire Nitro+ RX 7900 XTX"
                        },
                        new
                        {
                            Id = 14,
                            Gia = 17500000,
                            TenSanPham = "VGA ASUS TUF Gaming RTX 4070"
                        },
                        new
                        {
                            Id = 15,
                            Gia = 11500000,
                            TenSanPham = "VGA Colorful iGame RTX 4060 Ti Ultra W"
                        },
                        new
                        {
                            Id = 16,
                            Gia = 10500000,
                            TenSanPham = "CPU AMD Ryzen 7 7800X3D"
                        },
                        new
                        {
                            Id = 17,
                            Gia = 14500000,
                            TenSanPham = "CPU AMD Ryzen 9 7950X"
                        },
                        new
                        {
                            Id = 18,
                            Gia = 11200000,
                            TenSanPham = "CPU Intel Core i7-14700K"
                        },
                        new
                        {
                            Id = 19,
                            Gia = 8200000,
                            TenSanPham = "CPU Intel Core i5-13600K"
                        },
                        new
                        {
                            Id = 20,
                            Gia = 6000000,
                            TenSanPham = "CPU AMD Ryzen 5 7600X"
                        },
                        new
                        {
                            Id = 21,
                            Gia = 18000000,
                            TenSanPham = "Mainboard ASUS ROG Crosshair X670E Hero"
                        },
                        new
                        {
                            Id = 22,
                            Gia = 6500000,
                            TenSanPham = "Mainboard Gigabyte B650 AORUS ELITE AX"
                        },
                        new
                        {
                            Id = 23,
                            Gia = 4800000,
                            TenSanPham = "Mainboard MSI MAG B760M MORTAR WIFI"
                        },
                        new
                        {
                            Id = 24,
                            Gia = 22000000,
                            TenSanPham = "Màn hình LG UltraGear 27GR95QE OLED 240Hz"
                        },
                        new
                        {
                            Id = 25,
                            Gia = 28500000,
                            TenSanPham = "Màn hình Alienware AW3423DWF QD-OLED"
                        },
                        new
                        {
                            Id = 26,
                            Gia = 7500000,
                            TenSanPham = "Màn hình ASUS TUF Gaming VG27AQ 2K 165Hz"
                        },
                        new
                        {
                            Id = 27,
                            Gia = 16900000,
                            TenSanPham = "Màn hình BenQ Zowie XL2566K 360Hz"
                        },
                        new
                        {
                            Id = 28,
                            Gia = 3790000,
                            TenSanPham = "Chuột Logitech G Pro X Superlight 2"
                        },
                        new
                        {
                            Id = 29,
                            Gia = 3590000,
                            TenSanPham = "Chuột Razer DeathAdder V3 Pro"
                        },
                        new
                        {
                            Id = 30,
                            Gia = 3990000,
                            TenSanPham = "Chuột Zowie EC2-CW Wireless"
                        },
                        new
                        {
                            Id = 31,
                            Gia = 2400000,
                            TenSanPham = "Chuột Pulsar X2V2 Mini Wireless"
                        },
                        new
                        {
                            Id = 32,
                            Gia = 5500000,
                            TenSanPham = "Bàn phím Wooting 60HE Analog"
                        },
                        new
                        {
                            Id = 33,
                            Gia = 4900000,
                            TenSanPham = "Bàn phím Keychron Q1 Pro Wireless Custom"
                        },
                        new
                        {
                            Id = 34,
                            Gia = 5200000,
                            TenSanPham = "Bàn phím Corsair K70 MAX Magnetic"
                        },
                        new
                        {
                            Id = 35,
                            Gia = 4500000,
                            TenSanPham = "Bàn phím Razer Huntsman V3 Pro TKL"
                        },
                        new
                        {
                            Id = 36,
                            Gia = 3990000,
                            TenSanPham = "Tai nghe HyperX Cloud III Wireless"
                        },
                        new
                        {
                            Id = 37,
                            Gia = 3200000,
                            TenSanPham = "Tai nghe Logitech G733 Lightspeed"
                        },
                        new
                        {
                            Id = 38,
                            Gia = 5200000,
                            TenSanPham = "RAM Corsair Dominator Titanium 32GB 6000MHz"
                        },
                        new
                        {
                            Id = 39,
                            Gia = 3800000,
                            TenSanPham = "Nguồn Seasonic Focus GX-850 850W Gold"
                        },
                        new
                        {
                            Id = 40,
                            Gia = 7500000,
                            TenSanPham = "Tản nhiệt nước NZXT Kraken Elite 360 RGB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
