// <auto-generated />
using Buoi1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Buoi1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312063207_TenMigration")]
    partial class TenMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Buoi1.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Gia")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Gia = 55000000,
                            HinhAnh = "https://cdn2.cellphones.com.vn/x/media/catalog/product/v/g/vga_35_.png",
                            TenSanPham = "VGA ASUS ROG Strix 4090"
                        },
                        new
                        {
                            Id = 2,
                            Gia = 15000000,
                            HinhAnh = "https://kccshop.vn/media/product/28247_cpu_intel_core_i9_14900k.jpg",
                            TenSanPham = "CPU Intel Core i9-14900K"
                        },
                        new
                        {
                            Id = 3,
                            Gia = 6500000,
                            HinhAnh = "https://memoryzone.com.vn/wp-content/uploads/2023/11/ram-pc-g-skill-trident-z5-rgb-64gb-32gbx2-ddr5-6400mhz-black-1.jpg",
                            TenSanPham = "RAM G.Skill Trident Z5 RGB 64GB"
                        },
                        new
                        {
                            Id = 4,
                            Gia = 25000000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/z790-godlike_2195cfdc3f5748739e5b3e8bc5cca499_grande.png",
                            TenSanPham = "Mainboard MSI Z790 Godlike"
                        },
                        new
                        {
                            Id = 5,
                            Gia = 4500000,
                            HinhAnh = "https://image.hsv-tech.io/1920x0/tgdd/products/common/dc41820e-89ff-49c3-9476-65b8e16186bb.webp",
                            TenSanPham = "SSD Samsung 990 Pro 2TB"
                        },
                        new
                        {
                            Id = 6,
                            Gia = 4200000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/rm1000x_shift_4aacdb3c4a584e29b95d97d63f0e9bb5_grande.png",
                            TenSanPham = "Nguồn Corsair RM1000x"
                        },
                        new
                        {
                            Id = 7,
                            Gia = 4000000,
                            HinhAnh = "https://nzxt.com/assets/cms/34299/1695426388-h9-flow-black-pdp-main-1.png",
                            TenSanPham = "Case NZXT H9 Flow"
                        },
                        new
                        {
                            Id = 8,
                            Gia = 32000000,
                            HinhAnh = "https://images.samsung.com/is/image/samsung/p6pim/vn/lc49g95tssexxv/gallery/vn-odyssey-g9-g95ts-lc49g95tssexxv-530838690",
                            TenSanPham = "Màn hình Samsung Odyssey G9"
                        },
                        new
                        {
                            Id = 9,
                            Gia = 3990000,
                            HinhAnh = "https://hyberx.com.vn/wp-content/uploads/2024/03/razer-viper-v3-pro.jpg",
                            TenSanPham = "Chuột Razer Viper V3 Pro"
                        },
                        new
                        {
                            Id = 10,
                            Gia = 2990000,
                            HinhAnh = "https://akko.vn/wp-content/uploads/2023/01/3098B-Plus-World-Tour-Tokyo-R2-1-scaled.jpg",
                            TenSanPham = "Phím cơ Akko MOD007"
                        },
                        new
                        {
                            Id = 11,
                            Gia = 32000000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/gv-n408saorus-m-16gd_a90c49c2c00441a5bdb9a461e9e7b34d_grande.png",
                            TenSanPham = "VGA Gigabyte AORUS RTX 4080 Super Master"
                        },
                        new
                        {
                            Id = 12,
                            Gia = 24500000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/rtx-4070-ti-super-16g-gaming-x-trio_38c96e04a0334ca388aa58d2b86e4c84_grande.png",
                            TenSanPham = "VGA MSI RTX 4070 Ti Super Gaming X Trio"
                        },
                        new
                        {
                            Id = 13,
                            Gia = 29000000,
                            HinhAnh = "https://memoryzone.com.vn/wp-content/uploads/2023/01/vga-sapphire-nitro-radeon-rx-7900-xtx-24gb-gddr6-1.jpg",
                            TenSanPham = "VGA Sapphire Nitro+ RX 7900 XTX"
                        },
                        new
                        {
                            Id = 14,
                            Gia = 17500000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/tuf-rtx4070-12g-gaming_b1d6e42d3e714e2295756a95e7cf1d81_grande.png",
                            TenSanPham = "VGA ASUS TUF Gaming RTX 4070"
                        },
                        new
                        {
                            Id = 15,
                            Gia = 11500000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/igame-geforce-rtx-4060-ti-ultra-w-duo-oc-8g-v2_09e8f8e6b56f433cba0e3ea76c8dca9b_grande.png",
                            TenSanPham = "VGA Colorful iGame RTX 4060 Ti Ultra W"
                        },
                        new
                        {
                            Id = 16,
                            Gia = 10500000,
                            HinhAnh = "https://image.hsv-tech.io/1920x0/tgdd/products/common/7e1add6c-9b3a-41a4-b53d-21de77742c88.webp",
                            TenSanPham = "CPU AMD Ryzen 7 7800X3D"
                        },
                        new
                        {
                            Id = 17,
                            Gia = 14500000,
                            HinhAnh = "https://memoryzone.com.vn/wp-content/uploads/2022/09/cpu-amd-ryzen-9-7950x-16-core-32-thread-1.jpg",
                            TenSanPham = "CPU AMD Ryzen 9 7950X"
                        },
                        new
                        {
                            Id = 18,
                            Gia = 11200000,
                            HinhAnh = "https://memoryzone.com.vn/wp-content/uploads/2023/10/cpu-intel-core-i7-14700k-box-1.jpg",
                            TenSanPham = "CPU Intel Core i7-14700K"
                        },
                        new
                        {
                            Id = 19,
                            Gia = 8200000,
                            HinhAnh = "https://memoryzone.com.vn/wp-content/uploads/2022/10/cpu-intel-core-i5-13600k-1.jpg",
                            TenSanPham = "CPU Intel Core i5-13600K"
                        },
                        new
                        {
                            Id = 20,
                            Gia = 6000000,
                            HinhAnh = "https://memoryzone.com.vn/wp-content/uploads/2022/09/cpu-amd-ryzen-5-7600x-6-core-12-thread-1.jpg",
                            TenSanPham = "CPU AMD Ryzen 5 7600X"
                        },
                        new
                        {
                            Id = 21,
                            Gia = 18000000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/rog-crosshair-x670e-hero_0f34a7f36c674b259ef3fcff7acea671_grande.png",
                            TenSanPham = "Mainboard ASUS ROG Crosshair X670E Hero"
                        },
                        new
                        {
                            Id = 22,
                            Gia = 6500000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/b650-aorus-elite-ax_c5d2cf2eb79e4b7a98ebc3c0d3a33d73_grande.png",
                            TenSanPham = "Mainboard Gigabyte B650 AORUS ELITE AX"
                        },
                        new
                        {
                            Id = 23,
                            Gia = 4800000,
                            HinhAnh = "https://product.hstatic.net/200000722513/product/mag-b760m-mortar-wifi_e11deef10e4b47e293dd2c5b3bca2979_grande.png",
                            TenSanPham = "Mainboard MSI MAG B760M MORTAR WIFI"
                        },
                        new
                        {
                            Id = 24,
                            Gia = 22000000,
                            HinhAnh = "https://www.lg.com/vn/images/monitors/md08003461/gallery/medium02.jpg",
                            TenSanPham = "Màn hình LG UltraGear 27GR95QE OLED 240Hz"
                        },
                        new
                        {
                            Id = 25,
                            Gia = 28500000,
                            HinhAnh = "https://i.dell.com/sites/csimages/App-Merchandizing_Images/all/aw3423dwf.png",
                            TenSanPham = "Màn hình Alienware AW3423DWF QD-OLED"
                        },
                        new
                        {
                            Id = 26,
                            Gia = 7500000,
                            HinhAnh = "https://dlcdnwebimgs.asus.com/gain/61e36f3f-08a3-4f6e-8a49-25b7bb4fa08e/",
                            TenSanPham = "Màn hình ASUS TUF Gaming VG27AQ 2K 165Hz"
                        },
                        new
                        {
                            Id = 27,
                            Gia = 16900000,
                            HinhAnh = "https://zowie.benq.com/content/dam/zowie/products/gaming-monitor/xl2566k/xl2566k_pdp_01.jpg",
                            TenSanPham = "Màn hình BenQ Zowie XL2566K 360Hz"
                        },
                        new
                        {
                            Id = 28,
                            Gia = 3790000,
                            HinhAnh = "https://resource.logitech.com/w_692,c_lpad,ar_4:3,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/mice/g-pro-x-superlight-2/gallery/g-pro-x-superlight-2-top-black.png",
                            TenSanPham = "Chuột Logitech G Pro X Superlight 2"
                        },
                        new
                        {
                            Id = 29,
                            Gia = 3590000,
                            HinhAnh = "https://hyberx.com.vn/wp-content/uploads/2023/03/razer-deathadder-v3-pro-black.jpg",
                            TenSanPham = "Chuột Razer DeathAdder V3 Pro"
                        },
                        new
                        {
                            Id = 30,
                            Gia = 3990000,
                            HinhAnh = "https://zowie.benq.com/content/dam/zowie/products/mouse/ec2-cw/ec2-cw_pdp_01.jpg",
                            TenSanPham = "Chuột Zowie EC2-CW Wireless"
                        },
                        new
                        {
                            Id = 31,
                            Gia = 2400000,
                            HinhAnh = "https://www.pulsargg.com/cdn/shop/files/X2V2_Mini_Wireless_Black_1.jpg",
                            TenSanPham = "Chuột Pulsar X2V2 Mini Wireless"
                        },
                        new
                        {
                            Id = 32,
                            Gia = 5500000,
                            HinhAnh = "https://wooting.io/wp-content/uploads/2022/09/60HE-hero-side-right-3.png",
                            TenSanPham = "Bàn phím Wooting 60HE Analog"
                        },
                        new
                        {
                            Id = 33,
                            Gia = 4900000,
                            HinhAnh = "https://cdn.shopify.com/s/files/1/0059/0630/1017/files/Keychron-Q1-Pro-QMK-VIA-wireless-custom-mechanical-keyboard-for-Mac-and-Windows-with-hot-swappable-keychron-K-Pro-switch-carbon-black.jpg",
                            TenSanPham = "Bàn phím Keychron Q1 Pro Wireless Custom"
                        },
                        new
                        {
                            Id = 34,
                            Gia = 5200000,
                            HinhAnh = "https://www.corsair.com/medias/sys_master/images/images/hb1/hf3/9543022723102/CH-9109411-NA-Gallery-K70-MAX-RGB-01.png",
                            TenSanPham = "Bàn phím Corsair K70 MAX Magnetic"
                        },
                        new
                        {
                            Id = 35,
                            Gia = 4500000,
                            HinhAnh = "https://hyberx.com.vn/wp-content/uploads/2023/11/razer-huntsman-v3-pro-tkl.jpg",
                            TenSanPham = "Bàn phím Razer Huntsman V3 Pro TKL"
                        },
                        new
                        {
                            Id = 36,
                            Gia = 3990000,
                            HinhAnh = "https://media.kingston.com/hyperx/product/hx-product-headset-cloud-iii-wireless-black-1-zm-lg.jpg",
                            TenSanPham = "Tai nghe HyperX Cloud III Wireless"
                        },
                        new
                        {
                            Id = 37,
                            Gia = 3200000,
                            HinhAnh = "https://resource.logitech.com/w_692,c_lpad,ar_4:3,q_auto,f_auto,dpr_1.0/d_transparent.gif/content/dam/logitech/en/products/gaming-headsets/g733/gallery/g733-lightspeed-gallery-1-black.png",
                            TenSanPham = "Tai nghe Logitech G733 Lightspeed"
                        },
                        new
                        {
                            Id = 38,
                            Gia = 5200000,
                            HinhAnh = "https://www.corsair.com/medias/sys_master/images/images/h0e/h24/9467887575070/CMP32GX5M2B6000C30-Gallery-Dominator-Titanium-DDR5-RGB-Black-01.png",
                            TenSanPham = "RAM Corsair Dominator Titanium 32GB 6000MHz"
                        },
                        new
                        {
                            Id = 39,
                            Gia = 3800000,
                            HinhAnh = "https://seasonic.com/uploads/products/FOCUS-GX-850_01.png",
                            TenSanPham = "Nguồn Seasonic Focus GX-850 850W Gold"
                        },
                        new
                        {
                            Id = 40,
                            Gia = 7500000,
                            HinhAnh = "https://nzxt.com/assets/cms/34299/1662485331-kraken-elite-rgb-360-black-pdp-main-1.png",
                            TenSanPham = "Tản nhiệt nước NZXT Kraken Elite 360 RGB"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
